version: '3.9'

services:
  redis_server_tls:
    container_name: redis-tls
    image: redis:${REDIS_TAG}
    volumes:
      - ./redis/certs/server.crt:/etc/certs/redis.crt
      - ./redis/certs/server.key:/etc/certs/redis.key
      - ./redis/certs/ca.crt:/etc/certs/ca.crt
    ports:
      - "6380:6380"
    command:
      - redis-server
      - "--bind 0.0.0.0 ::"
      - --requirepass public
      - --tls-port 6380
      - --tls-cert-file /etc/certs/redis.crt
      - --tls-key-file /etc/certs/redis.key
      - --tls-ca-cert-file /etc/certs/ca.crt
      - --tls-protocols "TLSv1.3"
      - --tls-ciphersuites "TLS_CHACHA20_POLY1305_SHA256"
    restart: always
    networks:
      emqx_bridge:
