name: Check Rebar Dependencies

on: [pull_request, push]

jobs:
  check_deps_integrity:
    runs-on: ubuntu-20.04
    container: ghcr.io/emqx/emqx-builder/5.0-5:1.13.2-24.1.5-4-ubuntu20.04

    steps:
      - uses: actions/checkout@v2
      - name: Run check-deps-integrity.escript
        run: ./scripts/check-deps-integrity.escript
