# FIXME: temporary workflow for testing; remove later
name: Elixir Build (temporary)

concurrency:
  group: mix-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/emqx/emqx-builder/5.0-3:24.1.5-3-alpine3.14

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: setup mix
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get
      - name: produce emqx.conf.all template
        run: make conf-segs
      - name: elixir release
        run: mix release --overwrite
      - name: start release
        run: |
          cd _build/dev/rel/emqx
          bin/emqx start
      - name: check if started
        run: |
          sleep 10
          nc -zv localhost 1883
          cd _build/dev/rel/emqx
          bin/emqx ping
          bin/emqx ctl status
