name: Run static checks

concurrency:
  group: static-check-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    tags:
      - v*
      - e*
  pull_request:

jobs:
    run_static_analysis:
      runs-on: self-hosted
      container: "ghcr.io/emqx/emqx-builder/5.0-3:24.1.5-3-alpine3.14"
      steps:
      - uses: actions/checkout@v2
      - name: xref
        run: make xref
      - name: dialyzer
        run: make dialyzer
