name: Spellcheck

on:
  workflow_run:
    workflows: [Build slim packages]
    types:
      - completed

jobs:
  spellcheck_schema:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name:  emqx-24.2.1-1-ubuntu20.04
        workflow: build_slim_packages.yaml
        path: .
    - name: Run spellcheck
      run: |
        tar zxf *.tar.gz
        find . -name schema.json -exec scripts/spellcheck \{\} \;
